### ISSUE TITLE
A guest is able to create a direct chat with another guest

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1083]
Related to #333

# Precondition
Guest1 and Guest2 are in the same company with the "Guest" role.

# Actual Result
Guest2 is able to create a new direct chat with Guest1
![Peek 2021-03-30 14-15.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9506777d-8908-4ef7-9a63-34db6ab91fcf)

# Expected Result
The guest should be able to create a direct chat only with a non-guest user

# Environment
QA environment

**Comment by chamerling** [comment]
@BenoitTallandier can we clarify the spec on this?
In another issue we said that the guest can only mention user which are in the current channel. If a guest can be in several channels, it should be able to create discussions only with users which belongs to the same channels as him.

For example:

- guest1 is member of channelA. channelA members are user1, user2, user3 and guest1
- guest1 is member of channelB. channelB members are user3, user4, user5, guest1, guest2
- guest2 is member of channelC. channelC members are user3, user4, user6, user7, guest2

guest1 should be able to create direct chat with:  user1, user2, user3, user4, user5 and guest2 ie all members of channelA + all members of channelB

If a direct chat is created with some peer and if the peer leaves a channel guest was in, it does not mutate the direct chat:

- guest1 created a direct chat with user1 because they were both in channelA
- user1 leaves channelA
- direct chat between guest1 and user1 is still available

**Comment by BenoitTallandier** [comment]
It's exactly that. 
What we want to avoid is :
A agency that works with 2 freelance : 
Guest1 (a designer in freelance) is invited in channel A
Guest2 (a copywriter in freelance) is invited in channel B,
Guest1 & Guest2 shouldn't be able to interact or even see each other in the workspace. 

So what you propose is totally align the business case :)
