### ISSUE TITLE
Inviter name is not shown correctly in invitation-to-workspace email 

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1148]
**Describe the bug**
Instead of displaying name of the inviter, system shows () in invitation email

**To Reproduce**
1. Login to Twake web https://web.qa.twake.app/
2. Click on Add colleagues button
3. Fill in the email address of the invitee
4. Add

**Expected behavior**
Invitation email is sent to invitee with correct information

**Screenshots**
![2021-04-14_10-52.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/378cfdd4-7795-41f3-83c8-379d2d486911)

**Comment by tuanlc** [comment]
This issue happens when invitees are invited by Twake application. And currently, the inviter information is detected by requester. In this case, is Twake app, that does not have a name and email.
So, basically, to handle this issue, we need to do:
1. Twake Console needs to support invitation request from an application with the payload that contain inviter information
2. Twake will update code to add inviter information to the invitation request.

I created an issue for this in Twake console: https://ci.linagora.com/linagora/lgs/saas/portal/twake-console-account/issues/65

**Comment by RomaricMourgues** [comment]
Thanks Tuan Le :)

**Comment by tuanlc** [comment]
Hello @RomaricMourgues 
Twake Console has been released new version with the fix for you:

- http://account-twakeconsole.linagora.vn/apidoc/static/index.html#/user/post_api_companies__companyCode__users_invitation

Now, you can add inviter information in the invitation payload:
```json
{
  "emails": [
    "string"
  ],
  "inviter": {
    "name": "string",
    "email": "string"
  }
}
```

The fix was deployed to PREPROD (aka QA) platform. We expect to deploy it to PRODUCTION on Tuesday. So you can modify Twake app to adap this change.
