### ISSUE TITLE
Mobile/Unable to select company

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1211]
**Describe the bug**
User should be able to move from a certain company to other one in mobile view

**To Reproduce**
1. In Mobile device, login Twake web with an account that is member of different company
2. Try to move to another company to chat

**Expected behavior**
User should be able to move between companies

**Current behavior**
There is no way to do it

Tested in Iphone 11, safari/chrome

**Comment by RomaricMourgues** [comment]
@RkAiman you can work on this one

**Comment by chamerling** [comment]
There are many things to fix on responsive CSS, this one is important but there are also many others. Should be nice to have some work on this topic. WDYT @RomaricMourgues ?

**Comment by RomaricMourgues** [comment]
There is a small fix to have about how we use the height 100% on mobile.
On desktop height: 100vh represent all the webview height, so it works well.
On mobile it represent all the *screen* height, including searchbar and status bar of the phone. We should change the height of the app to have everything work again on responsive.

For your question @chamerling I don't want to put too many efforts on this because there is the native mobile development team. Responsive Twake should only be for edge user cases. If we can send and read message on Twake from mobile browser it is good for me, everything else is bonus only.

**Comment by chamerling** [comment]
Yes you are right, we should limit the responsive work, anyway there are some fixes to do, for example, here is what is displayed when I open a channel (so I guess it does not fit with "If we can send and read message on Twake from mobile browser it is good for me")

![Screenshot_2021-04-28-14-45-09-500_com android chrome](https://user-images.githubusercontent.com/264403/116407008-93b66480-a831-11eb-9de9-ec913192f723.jpg)
