### ISSUE TITLE
Guest Management > An external member cannot be invited to more than one channel 

### ISSUE THREAD

**Issue by tlle14** [linagora/Twake#1272]
# Precondition 
Story: https://github.com/linagora/Twake/issues/333
The external user has been invited to a channel 

# Actual Result
When inviting the external user to the second channel (either in the same workspace or in a different workspace with the 1st channel), the external user cannot see the invitation email.
The second channel doesn't appear for the external user

# Expected Result
Please confirm if 1 external user is able to join 1 or more channels.

# Environment
QA environment

**Comment by chamerling** [comment]
@BenoitTallandier please clarify this:

- When guest is already in a channel and is added in another channel, do we need to send an email? I guess yes, but the process is completely different: We do not have to send the same email, we just need to send an email saying that he has been added to a new channel, that's all since the user is already registered and provisioned on Twake Console and Chat.

**Comment by BenoitTallandier** [comment]
If a guest is invited to a chat channel at a company where the guest is already present, there is no need for an email: the user can see the second channel easily in the interface.

If a guest is invited in a new company, there we can send an email because switching between company is quite hidden.

**Comment by BenoitTallandier** [comment]
It is fixed

**Comment by BenoitTallandier** [comment]
It is fixed
