### ISSUE TITLE
On-boarding Tour disappeared

### ISSUE THREAD

**Issue by shivam9593** [linagora/Twake#1773]
When I create a new account on Twake - I can no longer see product tours (through Usetiful) anymore!

**Comment by BenoitTallandier** [comment]
Done

**Comment by shivam9593** [comment]
The on-boarding tour has disappeared again!

I think we should switch from Usetiful to something else because we consistently face issue with this.

**Comment by RomaricMourgues** [comment]
Did you use a private browser ? Because it works only once by browser (I saw it just today so it is strange)

**Comment by shivam9593** [comment]
Yes we tried on an incognito window. 

Also i think it should not work once per browser but once per email address.

**Comment by BenoitTallandier** [comment]
It was fixed on the URL `web.twake.app` but not on `beta.twake.app`. It is fixed with both URL now.
By the way, we should redirect automatically user from `beta.twake.app` to `web.twake.app` in the future :)

> Also i think it should not work once per browser but once per email address.
I agree, it's it just more work to do in term of integration. We can put it in the backlog and do it when we have time :)
