### ISSUE TITLE
Caldav support 

### ISSUE THREAD

**Issue by SamirSaidani** [linagora/Twake#208]
We don't want to use a proprietary protocol for dealing with business events and tasks, they are confidential to the business. We want to avoid using different calendar/tasks protocols for the same use : one for twake, one for nextcloud. 

We want to host the calendar / tasks server on our own site, as a central server, for instance with our nextcloud instance using caldav protocol. 

Please support the caldav opensource protocol.

**Comment by jhjacobs81** [comment]
I agree :) opensource protocol support should be maybe possible as a plugin/module so Twake administrators can choose ;-)

**Comment by BenoitTallandier** [comment]
We won't integrate caldav protocol directly inside Twake chat. This year, we will integrate https://github.com/linagora/openpaas-esn with the calendar part. It will replace our current calendar. So caldav we'll be supported.
I close this issue, not because we won't have this feature, but because it's related to an other task
