### ISSUE TITLE
Documents, calendar and tasks not showing

### ISSUE THREAD

**Issue by selimsandal** [linagora/Twake#2200]
I set up the server yesterday, but since then I can't see the documents, calendar and tasks menus. Is there some configuration I need to do before seeing them?

I posted this question under my other issue but migrating to a new one to document it.

**Comment by RomaricMourgues** [comment]
Hi, yes the simple installation version doesn't support documents calendar and tasks because they are deprecated unfortunately. We are going to focus on external integration in the future and integrate with softwares like LinShare for files for instance.
To install Documents Calendar and Tasks you'll need this docker-compose: https://github.com/linagora/Twake/blob/canary/twake/docker-compose.onpremise.yml

**Comment by selimsandal** [comment]
Thanks for the help @RomaricMourgues. In the future when those features with newer integrations get integrated into simple install, will we be able to switch to the newer versions without data loss? If not, I shouldn't install this one I guess.

**Comment by RomaricMourgues** [comment]
There is no reason to get data loss if you install Twake now and update it later. But if you install the [docker-compose.onpremise.yml](https://github.com/linagora/Twake/blob/canary/twake/docker-compose.onpremise.yml) and then want to update on the mongo one, then it will not work as scylla db and mongo db are not compatible.

**Comment by selimsandal** [comment]
> if you install Twake now and update it later

Got it, but since it's deprecated the version with calendar and files will not get updated right?
