### ISSUE TITLE
[Content Display] Frontend: create hooks and view for list of medias / list of files with pagination

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2403]
US: https://www.notion.so/linagora/Content-display-An-image-gallery-30475bbbac704d69a9654bf8e944cd24

Reusing the widgets built for the search modal, create a view (as modal) to list channel medias and files with pagination.

--

Here is mockups of this modal:
<img width="735" alt="Screenshot 2022-07-08 at 12 19 22" src="https://user-images.githubusercontent.com/14353924/177973682-d37b2f50-2293-4410-a352-6995591dea8c.png">

![Screenshot 2022-07-08 at 12 20 49](https://user-images.githubusercontent.com/14353924/177974540-a8f0bc03-2e2d-42ce-b0f9-8ffe12982cb7.png)

--

- [ ] It should reuse the existing atoms
- [ ] An atom must be created from the file-result.tsx element of the search box popup (move it to molecule)
- [ ] The "Participants" button must be replaced by three icons: a info button that open the channel parameters (if the user is not guest) ; a file button that open the popup of this issue ; a users icon that open the participants modal (previous "participants" text action)
- [ ] The hooks used for search can be reused or duplicated (the search input should not be used in this view)
- [ ] Pagination must be implemented (if backend works)

**Comment by tprudentova** [comment]
Hi @rezk2ll 
When you send a picture to the channel and open Channel files and medias straight away, the Files page is empty. The same way if you send a file, the Medias page is empty. The problem is solved by refreshing the page. 
https://images.zenhubusercontent.com/271994210/890b7eff-efea-47f5-97fa-9757f4b2f96d/vid_20220902_115344_kk0tht0f.mp4
