### ISSUE TITLE
We need to test a new Twake mobile build 1.1.4

### ISSUE THREAD

**Issue by EvGen94** [linagora/Twake#2457]
### **Gallery redesign - Four ways of uploading files**
- First go to gallery select a file then send 
- Second go to gallery select a file write a comment then send 
- Thied go to gallery - Twake files select and send 
- Fourth go to gallery - local storage select a file 
### **Chat screen redesign**
- Check all message bubbles, colors, last 3 avatars of user in thread section, smoothness, how images look wide one and narrow and so on 

### **Long press message animation**  
- We have a new entity with action which user can perform on a message when long press it, check all actions and animation and scroll positions

**Comment by tprudentova** [comment]
Sending files
1.	Sending a wide/tall picture from the gallery: it is certainly less than 75% of its size, looks very cropped to me (probably was meant to be like that? Anyway, here are the screenshots of pics being cropped, 2560x1989 px and 397x1871 px accordingly)
![1661781779456.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/d85f99c0-2c3b-4589-a8d4-781b4068db6b)![1661781779398.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/2ece6773-dc39-4cbe-8001-5debdace2396)

![1661781779226.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/44adfd66-321a-45ee-bbc1-b102181e92b2)![1661781779172.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/538b9aa6-25f6-4df2-b674-f4005bf79732)

2.	And when a “normal size” picture is sent, it is also cropped (pic in the screenshot is a standard-sized photo taken from my phone)
![1661781780072.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/5b6fca04-421b-4bcc-8965-538a23d1d6b2)
![1661781779048.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/0ea9d218-8cd7-46c9-9d6e-664631b9851c)
3.	An almost square picture is cropped to be extremely tall, like pics with 2/3 ratio
![1661781780152.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/d276d79a-10ab-4f7e-bebf-83ad7369439b)
![1661781780112.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/d45f3c45-eda6-4341-87b4-221eb28eadcc)
4.	And here is a screenshot of a tall picture that isn’t cropped at all (474x917px, so the ratio is almost 1/2). In fact, looks like a picture of this ratio is the only one that doesn’t get cropped at all which I personally find weird, cause this ratio is not, so to speak, standard
![1661781779339.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/186e1948-4a99-48c3-ad17-25e1679286aa)
![1661781779282.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/56f9a638-86c8-4e0d-9406-ada693d27233)
5.	When I tried to choose pictures to upload, the paste button in the comment field didn’t work. Tried to do the same thing after a while and it worked 
https://images.zenhubusercontent.com/271994210/245bb27d-8875-42bf-971a-eb1e3ad79d09/screenrecorder_2022_08_29_03_20_32_842.mp4
6.	Same problem Diana already described – I press Send once but the message with attachments is sent twice
7.	When you send a message with a comment, for a few seconds it is displayed like this: 2 grey squares with time and delivery status in between. Then it turns normal 
![HnomrpKOS_vmav7B8xSsmfVy02CCCHhGN-59LoIQ1pOlBp_9iOa7ZV2GZ2An2l5Smk2H6ZfRoWnSOkucSe8gLjUH.jpeg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/066f1932-cae7-4edc-8b9d-e497ee296e3e)
8.	When you send one file of any kind after another with no comment, they are united into one single message, even if the time of sending is different (for these 2 it was 2:17 and 2:19). If you send a file with a comment, it is sent as a separate message (NB: I tried to imitate the same path later and files were sent properly as separate messages. The files that got united into one message before stayed united)
![1661781779113.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/ec385be7-22b1-42a5-b6a0-b1dbe0a98af6)
![1661781779951.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/4fdc4a62-10cb-4f88-9178-8069764f645d)
9.	When you send a file from internal storage (I checked with docx, pdf, odt, rtf, xlsx) there is no preview and name of the document is visible. The download button for the file also isn’t there until you close the app and open it again. However, everything works just fine for pptx (NB: I tried to imitate the same path later and the download button was there. Still no preview or name, however)
![1661781779912.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/c417fc21-2ed6-48d8-a87e-befae0205be3)
![1661781779830.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/945d4019-1448-488b-b8ff-bd71c4b72a3f)
10.	This warning appeared quite out of nowhere at a random time when I tried to open the gallery view. The permissions are granted, worked fine before, worked fine after I closed gallery view and opened it again
![1661781779739.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/a8ea646a-7b29-46ae-86db-8312d59af9ba)
11.	The name of the sender in Twake files isn’t visible
![1661781779633.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/c1128598-35e7-4252-9bc1-9cffacac204f)

Long press
1.	Path: long press the message, press Back on your device (for me it’s a left to right swipe), leave the chat, open any chat again -> greyed out screen as in the screenshot, impossible to interact with. Fixed by closing the app and opening it again
![1661781780192.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/47bbbb00-beff-4f0a-97b3-88582d650390)
2.	If you long press a message with a single image or file as in the screenshots below, the reactions are so far above you can’t either see them or interact with them
![N9dKzSb2N5W_vt2sM674htDFEohGKxlex9xKXBLfrREXbO8gbGO_KVWAdpkAqjlK5awP82uYW08JvYnQG_miKMnu.jpeg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/7ec8f0ae-9448-4f69-9ad8-afe3e076aa06)
3.	If you long press a message with lots of items, it’s vice versa, the delete button is so far bellow it gets cropped out
![1661781779688.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/3a5e75ee-37e7-4b50-902d-0cb18ae4d955)
4.	Edit (nice to have): when you press edit, it looks like you have an opportunity to add a picture to the message, but when you try to do so, it is sent as a separate message
5.	Edit (nice to have): it is possible to edit a deleted message (Text “Deleted message”). However, if you try to edit this text and press Send, nothing changes in the message, so the Edit option probably shouldn’t exist for deleted messages
6.	Copy (nice to have): the option Copy exists for messages that only include images, and pressing it doesn’t do anything, so it’s probably best to get rid of this option for such messages
7.	Pinned message: when you press on the list of pinned messages on top, if the chosen pinned message is a long text or a picture, you jump to the message and it’s shown in a rather weird way, it is not displayed at the top of the screen but in the middle, so until you scroll you can only see half of it
![1661781779989.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/2729e41c-bfd3-4d63-8f74-ac55f7b65e49)
Threads
1.	When you choose to comment a long message (at least 1 image or file) and press on the message composer, it kinda overlaps the phrase “N comments”
https://images.zenhubusercontent.com/271994210/020b6ee7-4ddd-4639-9495-0dec64ef7990/screenrecorder_2022_08_29_14_54_01_29.mp4
2.	Also, when you choose to comment a long message (if there are no or few comments yet), a huge part of it is covered by the blank space for comments which looks weird
![1661781780030.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/42ef49f1-c0ff-48e8-b375-b0a74845a623)

**Comment by tprudentova** [comment]
Miscellaneous: 

On the screen with all channels the last visible message is the last message sent anywhere, in my case – a message from a thread ("It's a beautiful day outside"![1661783524789.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/74462066-d5d5-42e9-b498-ab9624d2c0d0)). 
![1661783524733.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/6b6a6205-28d4-43ba-9eba-7932bd314f05)
Shouldn’t it be more logical to display the last message sent “directly” in the channel? “Test” in my case. 
![1661783524842.jpg](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/d7b7e4c4-ca0c-4b69-9676-80581920c1e5)
Threads seem to be more of discussions separated from the main chat and I might even not be interested in the discussion happening in the thread

Nice to have: If you’re looking at older messages and type and send a new one, it would be logical to jump to the sent message (check twake vs telegram)
https://images.zenhubusercontent.com/271994210/f2aa1069-5a21-4687-9e6a-4aa3db269045/screenrecorder_2022_08_29_17_28_39_350.mp4
https://images.zenhubusercontent.com/271994210/841d74ef-b0f9-4304-99a6-beacab74eb05/screenrecorder_2022_08_29_17_29_37_781.mp4
Nice to have: When you send a file from twake files or internal storage it is impossible to add a description 

Nice to have: It is also impossible to choose several files from Twake files, would be nice to have such possibility
